#!/bin/bash

R=$(echo $DOCKER_TAG | cut -d "-" -f2)

if [ $DOCKER_TAG == "latest" ]
then
  docker build . --build-arg R=${DOCKER_TAG} -t ${IMAGE_NAME}
else
  docker build . --build-arg R=${R} -t ${IMAGE_NAME}
fi
